### ISSUE TITLE
Wrong type for an EFI System Partition (ESP)

### ISSUE THREAD

**Issue by W-Y-R** [nix-community/disko#528]
After running the script, with no apparent errors, I execute the nixos-install command. It ends up successfully (for some odd reason) building the system, despite the error below. Even so, after rebooting, the computer does not see any boot options and I have to redo everything again in the iso. Please take a look at my disko-config.nix and tell me what it is that I’m doing wrong.
```
Initializing machine ID from random generator.
File system "/dev/nvme0n1p1" has wrong type for an EFI System Partition (ESP).
1 Traceback (most recent call last):
File "/nix/store/60sp82.jbrspnffqnfz1mmr j6d84gbiza-systemd-boot/bin/systemd-boot-builder", line 356, in <module> main()
File "/nix/store/60sp82 jbrspnffqnfz1mmr j6d84gbiza-systemd-boot/bin/systemd-boot-builder", line 344, in main install bootloader (args)
File "/nix/store/60sp82.jbrspnffqnfz1mmr j6d84gbiza-systemd-boot/bin/systemd-boot-builder", line 269, in install_boot loader subprocess.check_call([f" (SYSTEMD)/bin/bootctl", f"--esp-path=(EFI_SYS_MOUNT_POINT)"]+ bootctl_flags + ["install"]) File "/nix/store/u4fuuhkzb0ssuefu5j34pw09f0qu848-python3-3.11.7/lib/python3.11/subprocess.py", line 413, in check_call raise CalledProcessError (retcode, cnd)
subprocess.CalledProcessError: Command '['/nix/store/3zuz5yunrrh8n6nqzgw3g1q6pilxcphq-systemd-255.2/bin/bootctl', '--esp-path=/boot', '—-no-variables', 'install'l' returned non-zero exit status 1. $setting up /etc...
$setting up /etc...
setting root password..
New password:
Retype new password:
passwd: password updated successfully
installation finished!
```
```
{ inputs, ... }: {
  imports = [ inputs.disko.nixosModules.disko ];
  disko.devices = {
    disk = {
      vbd = {
        device = "/dev/nvme0n1";
        type = "disk";
        content = {
          type = "table";
       	  format = "gpt";
          partitions = [
	    {
              name = "ESP";
	      start = "1MiB";
              end = "1G";
              content = {
		type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "defaults" ];
              };
            }
            {
              name = "swap";
              start = "1G";
              end = "9G";
              content = {
                type = "swap";
		resumeDevice = true;
                randomEncryption = true;
              };
            }
            {
	      name = "root";
              start = "9G";
	      end = "100%";
	      part-type = "primary";
              content = {
		type = "btrfs";
		extraArgs = [ "-f" ];
                subvolumes = {
                  "/nix" = {
                    mountOptions = [ "compress=zstd" "noatime" ];
                    mountpoint = "/nix";
                  };
                  "/persist" = {
                    mountOptions = [ "compress=zstd" "noatime" ];
                    mountpoint = "/persist";
                  };
                };
              };
            }
          ];
	    };
      };
    };
    nodev = {
      "/" = {
        fsType = "tmpfs";
        mountOptions = [
          "defaults"
          "size=8G"
          "mode=755"
        ];
      };
    };
  };

  fileSystems = {
    "/".neededForBoot = true;
    "/nix".neededForBoot = true;
    "/boot".neededForBoot = true;
    "/persist".neededForBoot = true;
  };
}
```

**Comment by W-Y-R** [comment]
This is what **df -h** returns after running the script.

| Filesystem    | Size  | Used | Avail | Use% | Mounted on     |
|---------------|-------|------|-------|------|----------------|
| devtmpfs      | 345M  | 0    | 345M  | 0%   | /dev           |
| tmpfs         | 3.4G  | 0    | 3.4G  | 0%   | /dev/shm       |
| tmpfs         | 3.4G  | 2M   | 1.7G  | 1%   | /run           |
| tmpfs         | 3.4G  | 960K | 3.4G  | 1%   | /run/wrappers  |
| /dev/root     | 950M  | 950M | 0     | 100% | /iso           |
| /dev/loop0    | 904M  | 904M | 0     | 100% | /nix/.ro-store |
| tmpfs         | 3.4G  | 571M | 2.9G  | 17%  | /nix/.rw-store |
| overlay       | 3.4G  | 571M | 2.9G  | 17%  | /nix/store     |
| tmpfs         | 8.0K  | 8.0K | 0     | 100% | /run/user      |
| none          | 8.0G  | 8.0G | 0     | 100% | /mnt           |
| /dev/nvmeOnlp1 | 13G | 952M | 12G  | 1%   | /mnt/boot      |
| /dev/nvmeOnlp3 | 469G | 467G | 2G   | 1%   | /mnt/nix       |
| /dev/nvmeOnlp3  | 469G | 467G | 2G   | 1%   | /mnt/persist   |

**Comment by itslychee** [comment]
You need to specify the type as shown in the `simple-efi` example

https://github.com/nix-community/disko/blob/f67ba6552845ea5d7f596a24d57c33a8a9dc8de9/example/simple-efi.nix#L11

**Comment by W-Y-R** [comment]
I did attempt that solution, but the EF00 type is incompatible with the partitions’ “list of” option (the “[…]” syntax).

I’m not sure if this a bug or is intended as a feature. I tried using curly braces to allow the type to work, but I don’t remember it working either.

Nevertheless, the source of the problem seems unlikely, given the availability of the square brackets option.

**Comment by W-Y-R** [comment]
This is what I ended up doing.
```
{
  disko.devices = {
    disk = {
      vda = {
        device = "/dev/nvme0n1";
        type = "disk";
        content = {
          type = "gpt";
          partitions = {
	      ESP = {
	      start = "1MiB";
	      end = "512MiB";
	      type = "EF00";
              content = {
		type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                #mountOptions = [ "defaults" ];
              };
            };
	      root = {
	      size = "100%";
	      #part-type = "primary";
              content = {
		type = "btrfs";
		extraArgs = [ "-f" ];
                subvolumes = {
                  "/nix" = {
                    mountOptions = [ "compress=zstd" "noatime" ];
                    mountpoint = "/nix";
                  };
                  "/persist" = {
                    mountOptions = [ "compress=zstd" "noatime" ];
                    mountpoint = "/persist";
                  };
                };
              };
            };
          };
	};
      };
    };
    nodev = {
      "/" = {
        fsType = "tmpfs";
        mountOptions = [
          "defaults"
          "size=8G"
          "mode=755"
        ];
      };
    };
  };

  fileSystems = {
    "/".neededForBoot = true;
    "/nix".neededForBoot = true;
    "/boot".neededForBoot = true;
    "/persist".neededForBoot = true;
  };
}
```
